<?php

/**
 * Supremecreative (Pty) Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to amir@supremecreative.co.za so I can send you a copy.
 *
 * @copyright   Copyright (c) 2017 Supremecreative (Pty) Ltd
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $helper = Mage::helper('giftregistry'); ?>
<?php $sessionFormData = Mage::getSingleton('core/session')->getGiftRegistryFormData(); ?>

<?php $defaultShippingAddress = $helper->getDefaultShippingAddress(); ?>

<?php if ($giftregistryInstance = $this->getGiftregistryInstance()) : ?>

<?php $giftregistryShipping = json_decode($giftregistryInstance->getShipping(), true);  ?>

    <h2 class="legend"><?php echo $this->__('Edit Gift Registry') ?></h2> 

    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <form action="<?php echo $this->getUrl('giftregistry/index/updatePost/id/' . $giftregistryInstance->getId() ) ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Event Information') ?></h2>  
            <p class="required">* Required Fields</p>

            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="type_id" class="required"><em>*</em><?php echo $this->__('Event type') ?></label>                    
                        <div class="input-box">                        
                            <select name="type_id" class="validate-select" id="type_id">
                                    <option value=""><?php echo $this->__('Please Select an Event Type') ?></option>
                                <?php foreach ($helper->getEventTypes() as $type): ?>
                                    <option id="<?php echo $type->getTypeId(); ?>" value="<?php echo $type->getTypeId(); ?>" <?php echo $type->getTypeId() == $giftregistryInstance->getTypeId() ?  'selected' : ''; ?>> <?php echo $type->getName(); ?>                               
                                    </option>
                                <?php endforeach; ?>
                                    <option value="custom"><?php echo $this->__('Create A Custom Gift Registry Type...') ?></option>                                
                            </select> 

                        </div>                   
                    </div>

                    <div class="field custom_event_type_id" id="custom_event_type_id">
                    <label for="custom_event_type_id" class="required"><em>*</em><?php echo $this->__('Specify Event type') ?></label>                    
                        <div class="input-box">                        
                            <input type="text" name="custom_event_type" id="custom_event_type" placeholder="Event Type" class="input-text" value="<?php echo isset($sessionFormData["custom_event_type_id"]) ?  $sessionFormData["custom_event_type_id"] : ''; ?>" title="Event Type"/>                                                 
                        </div>                   
                    </div>                 

                    <div class="field">
                    <label for="event_name" class="required"><em>*</em><?php echo $this->__('Registry Name') ?></label>                    
                        <div class="input-box">                        
                            <input type="text" name="event_name" id="event_name" placeholder="Registry Name" class="input-text required-entry" value="<?php echo isset($sessionFormData["event_name"]) ?  $sessionFormData["event_name"] : $giftregistryInstance->getEventName(); ?>" title="Registry Name"/>                                                 
                        </div>                   
                    </div>   

                    <div class="field">
                    <label for="registry_img"><?php echo $this->__('Image') ?></label>                    
                        <div class="input-box">                        
                            <input type="file" accept="image/*" name="registry_img" id="registry_img_input" class="input-text" value="<?php echo isset($sessionFormData["registry_img"]) ?  $sessionFormData["registry_img"] : ''; ?>" title="Image Upload">                                            
                        </div>                   
                    </div>

                    <div class="field">
                        <div class="input-box">                                       
                            <img id="registry_img_display" src="<?php echo isset($sessionFormData["registry_img"]) ?  $sessionFormData["registry_img"] : Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)  . 'giftregistryimgs/'  . $giftregistryInstance->getBannerImg(); ?>" alt="<?php echo isset($sessionFormData["event_name"]) ?  $sessionFormData["event_name"] : ''; ?>" height="260" width="365">                   
                        </div>                   
                    </div>

                    <div class="field">
                        <label class="giftreg" for="event_date"><?php echo $this->__('Event Date') ?></label>                    
                        <div class="input-box">                                       
                            <input type="text" name="event_date" id="datepicker" placeholder="Event Date" value="<?php echo isset($sessionFormData["event_date"]) ? $sessionFormData["event_date"] :  $giftregistryInstance->getEventDate(); ?>" title="Event Date"/>                                                
                        </div>                   
                    </div>                 

                    <div class="field">
                        <label class="giftreg" for="number_guests"><?php echo $this->__('Number Of Guests') ?></label>                    
                        <div class="input-box">                                       
                            <input type="text" name="number_guests" id="number_guests" value="<?php echo isset($sessionFormData["number_guests"]) ? $sessionFormData["number_guests"] : $giftregistryInstance->getNumberGuests(); ?>" title="Number Of Guests"/>                                                
                        </div>                   
                    </div>  

                    <div class="field">
                    <label class="giftreg" for="event_location"><?php echo $this->__('Event Location') ?></label>                     
                        <div class="input-box">                                       
                            <input type="text" name="event_location" id="event_location" value="<?php echo isset($sessionFormData["event_location"]) ? $sessionFormData["event_location"] :  $giftregistryInstance->getEventLocation(); ?>" title="Event Location"/>                                              
                        </div>                   
                    </div>   

                    <div class="field">
                    <label class="giftreg" for="event_message"><?php echo $this->__('Message') ?></label>   
                        <div class="input-box">                                       
                            <textarea name="event_message" rows="4" cols="40"><?php echo isset($sessionFormData["event_message"]) ? $sessionFormData["event_message"] : $giftregistryInstance->getEventMessage(); ?></textarea>                                             
                        </div>                                                 
                    </div>                 

                </li>
            </ul>
        </div>

        <div class="fieldset">

            <h2 class="legend"><?php echo $this->__('SHIPPING DETAILS') ?></h2>
            <ul class="form-list">

                <?php if(isset($giftregistryShipping["firstname"]) || isset($giftregistryShipping["lastname"]) ||  isset($giftregistryShipping["middlename"])): ?> 

                <div class="customer-name-middlename">
                    <li class="fields">
                        <div class="field name-firstname">
                            <label for="firstname" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
                            <div class="input-box">
                                <input type="text" name="firstname" value="<?php echo isset($giftregistryShipping["firstname"]) ? $giftregistryShipping["firstname"] : ''; ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('First Name')) ?>" class="input-text required-entry" id="firstname" />
                            </div>
                        </div>
                         <div class="field name-middlename">
                            <label for="middlename" class="required"><em>*</em><?php echo $this->__('Middle Name/Initial') ?></label>
                            <div class="input-box">
                                <input type="text" name="middlename" value="<?php echo isset($giftregistryShipping["middlename"]) ? $giftregistryShipping["middlename"] : ''; ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Middle Name/Initial')) ?>" class="input-text" id="middlename" />
                            </div>
                        </div>
                        <div class="field name-lastname">
                            <label for="lastname" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
                            <div class="input-box">
                                <input type="text" name="lastname" value="<?php echo isset($giftregistryShipping["lastname"]) ? $giftregistryShipping["lastname"] : '' ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Last Name')) ?>" class="input-text required-entry" id="lastname" />
                            </div>
                        </div>                    
                    </li>         
                </div>  

                <?php else: ?>

                <li class="fields">
                    <?php echo $helper->getNameBlockHtml() ?>
                </li>

                <?php endif ?>

                <li class="fields">
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" value="<?php echo $giftregistryShipping["telephone"] ? $giftregistryShipping["telephone"] : $this->escapeHtml($defaultShippingAddress->getTelephone()); ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $helper->getAddressEditBlock()->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                        </div>
                    </div>
                </li>

            <?php $_streetValidationClass = Mage::helper('customer/address')->getAttributeValidationClass('street'); ?>

            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>


                <li class="wide">
                    <label for="street_1"><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street_1" value="<?php echo isset($giftregistryShipping["street_1"]) ? $giftregistryShipping["street_1"] : $this->escapeHtml($defaultShippingAddress->getStreet(1))  ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>

                <li class="wide">
                    <label for="street_2"><?php echo $this->__('Street Address 2') ?></label>
                    <div class="input-box">
                        <input type="text" name="street_2" value="<?php echo isset($giftregistryShipping["street_2"]) ? $giftregistryShipping["street_2"] : $this->escapeHtml($defaultShippingAddress->getStreet(2))  ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_2" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>

                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" title="City" value="<?php echo isset($giftregistryShipping["city"]) ? $giftregistryShipping["city"] : $this->escapeHtml($defaultShippingAddress->getCity()) ?>" class="input-text <?php echo Mage::helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <input type="text" id="region" name="region" value="<?php echo isset($giftregistryShipping["region"]) ? $giftregistryShipping["region"] : '' ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo Mage::helper('customer/address')->getAttributeValidationClass('region') ?>" />  
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo isset($giftregistryShipping["postcode"]) ? $giftregistryShipping["postcode"] : '' ?>" title="Zip/Postal Code" id="zip" class="input-text validate-zip-international <?php echo Mage::helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box" name="country_id">
                            <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($giftregistryShipping["country_id"]) ?>
                        </div>
                    </div>
                </li>
            </ul>
        </div>    

        <div class="buttons-set">
            <button type="submit" title="Save" id="saveregbutton" class="button">
                <span>
                    <span><?php echo $this->__('Save & Continue') ?></span>
                </span>
            </button>
        </div>        

    </form>

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        var picker = new Pikaday({ field: document.getElementById('datepicker'),  minDate: new Date() });
    //]]>
    </script>

<?php endif; ?> 