<?php

/**
 * Supremecreative (Pty) Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to amir@supremecreative.co.za so I can send you a copy.
 *
 * @copyright   Copyright (c) 2017 Supremecreative (Pty) Ltd
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $helper = Mage::helper('giftregistry'); ?>
<?php $giftregistryInstance = $this->getGiftregistryInstance(); ?>
<?php $shipping = Mage::getBlockSingleton('giftregistry/onepage_shipping'); ?>

<?php if ($giftregistryInstance = $this->getGiftregistryInstance()) : ?>

    <h2 class="legend"><?php echo $this->__('Edit Gift Registry') ?></h2> 

    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <form action="<?php echo $this->getUrl('giftregistry/index/updatePost/id/' . $giftregistryInstance->getId() ) ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Event Information') ?></h2>  
            <p class="required">* Required Fields</p>

            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="type_id" class="required"><em>*</em><?php echo $this->__('Event type') ?></label>                    
                        <div class="input-box">                        
                            <select name="type_id" class="validate-select" id="type_id">
                                    <option value=""><?php echo $this->__('Please Select an Event Type') ?></option>
                                <?php foreach ($helper->getEventTypes() as $type): ?>
                                    <option id="<?php echo $type->getTypeId(); ?>" value="<?php echo $type->getTypeId(); ?>" <?php echo $type->getTypeId() == $giftregistryInstance->getTypeId() ?  'selected' : ''; ?>> <?php echo $type->getName(); ?>                               
                                    </option>
                                <?php endforeach; ?>
                                    <option value="custom"><?php echo $this->__('Create A Custom Gift Registry Type...') ?></option>                                
                            </select> 

                        </div>                   
                    </div>

                    <div class="field custom_event_type_id" id="custom_event_type_id">
                    <label for="custom_event_type_id" class="required"><em>*</em><?php echo $this->__('Specify Event type') ?></label>                    
                        <div class="input-box">                        
                            <input type="text" name="custom_event_type" id="custom_event_type" placeholder="Event Type" class="input-text" value="" title="Event Type"/>                                                 
                        </div>                   
                    </div>                 

                    <div class="field">
                    <label for="registrant_name" class="required"><em>*</em><?php echo $this->__('Registrant\'s Name(s)') ?></label>                    
                        <div class="input-box">                        
                            <input type="text" name="owner" id="owner" placeholder="Registrant's Name(s)" class="input-text required-entry" value="<?php echo $giftregistryInstance->getOwner() ? $giftregistryInstance->getOwner() : ''; ?>" title="Registrant's Name(s)"/>                                                 
                        </div>                   
                    </div>   

                    <div class="field">
                    <label for="registry_img"><?php echo $this->__('Image') ?></label>                    
                        <div class="input-box">                        
                            <input type="file" accept="image/*" name="registry_img" id="registry_img_input" class="input-text" value="<?php echo $giftregistryInstance->getRegistryImg() ? $giftregistryInstance->getRegistryImg() : ''; ?>" title="Image Upload">                                            
                        </div>                   
                    </div>

                    <div class="field">
                        <div class="input-box">                                       
                            <img id="registry_img_display" src="<?php echo $giftregistryInstance->getBannerImg() ?  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)  . 'giftregistryimgs/'  . $giftregistryInstance->getBannerImg() : ''; ?>" height="260" width="680">                  
                        </div>                   
                    </div>

                    <div class="field">
                        <label class="giftreg" for="event_date"><?php echo $this->__('Event Date') ?></label>                    
                        <div class="input-box">                                       
                            <input type="text" name="event_date" id="datepicker" placeholder="Event Date" value="<?php echo $giftregistryInstance->getEventDate() ? $giftregistryInstance->getEventDate() :  ''; ?>" title="Event Date"/>                                                
                        </div>                   
                    </div>                 

                    <div class="field">
                        <label class="giftreg" for="number_guests"><?php echo $this->__('Number Of Guests') ?></label>                    
                        <div class="input-box">                                       
                            <input type="text" name="number_guests" id="number_guests" value="<?php echo $giftregistryInstance->getNumberGuests() ? $giftregistryInstance->getNumberGuests() : ''; ?>" title="Number Of Guests"/>                                                
                        </div>                   
                    </div>  

                    <div class="field">
                    <label class="giftreg" for="event_location"><?php echo $this->__('Event Location') ?></label>                     
                        <div class="input-box">                                       
                            <input type="text" name="event_location" id="event_location" value="<?php echo $giftregistryInstance->getEventLocation() ? $giftregistryInstance->getEventLocation() :  ''; ?>" title="Event Location"/>                                              
                        </div>                   
                    </div>   

                    <div class="field">
                    <label class="giftreg" for="event_message"><?php echo $this->__('Message') ?></label>   
                        <div class="input-box">                                       
                            <textarea name="event_message" rows="4" cols="40"><?php echo $giftregistryInstance->getEventMessage() ? $giftregistryInstance->getEventMessage() : ''; ?></textarea>                                             
                        </div>                                                 
                    </div>                 

                </li>
            </ul>
        </div>

    <div class="fieldset">
        
        <h2 class="legend"><?php echo $this->__('SHIPPING DETAILS') ?></h2>
        <ul class="form-list">    
        <?php if ($shipping->customerHasAddresses()): ?>
        <li class="wide">
            <label for="billing-address-select"><?php echo $this->__('Select a shipping address from your address book.') ?></label>
            <div class="input-box">
                <?php echo $shipping->getShippingAddressesHtmlSelect('shipping') ?>
            </div>
        </li>
        <?php endif; ?>
         </ul>
    </div>  

        <div class="buttons-set">
            <button type="submit" title="Save" id="saveregbutton" class="button">
                <span>
                    <span><?php echo $this->__('Save & Continue') ?></span>
                </span>
            </button>
        </div>        

    </form>

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        var picker = new Pikaday({ field: document.getElementById('datepicker'),  minDate: new Date() });
    //]]>
    </script>

<?php endif; ?> 